apiVersion: v1
kind: Namespace
metadata:
  name: rollup
  labels:
    name: rollup
    app.kubernetes.io/name: rollup
    app.kubernetes.io/component: rollup-infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: ethereum
  labels:
    name: ethereum
    app.kubernetes.io/name: ethereum
    app.kubernetes.io/component: ethereum-infrastructure